apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.gitlabDataAccessMode | quote }}
  {{- if .Values.gitlabConfigStorageClass }}
  storageClassName: {{ .Values.gitlabConfigStorageClass | quote }}
  {{- end }}
  resources:
    requests:
      # Fallback to supporting older value: gitlabRailsStorageSize when the new one is not set
      storage: {{ coalesce .Values.gitlabDataStorageSize .Values.gitlabRailsStorageSize "30Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-registry-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.gitlabRegistryAccessMode | quote }}
  {{- if .Values.gitlabConfigStorageClass }}
  storageClassName: {{ .Values.gitlabConfigStorageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "30Gi" .Values.gitlabRegistryStorageSize }}
