apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-config-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.gitlabConfigAccessMode | quote }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.gitlabConfigStorageSize }}
  {{- if .Values.gitlabConfigStorageClass }}
  storageClassName: {{ .Values.gitlabConfigStorageClass | quote }}
  {{- end }}
