{{- if .Values.redisDedicatedStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "redis.fullname" . }}-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.redisAccessMode | quote }}
  {{- if .Values.gitlabConfigStorageClass }}
  storageClassName: {{ .Values.gitlabConfigStorageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "5Gi" .Values.redisStorageSize }}
{{- end }}
